# Generated by Django 5.0.1 on 2024-01-31 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Under Consideartion'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('done', 'Done'), ('future', 'In Future')], default='Under Consideration', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Voices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.URLField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SocialMediaContent.content')),
            ],
        ),
    ]
