# Generated by Django 5.0.1 on 2024-01-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialMediaContent', '0002_content_movie_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='movie_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
